name: Continues integration with nodejs

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: CLonar y ubicarse en la rama main
        uses: actions/checkout@v2
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar test
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: CLonar y ubicarse en la rama main
        uses: actions/checkout@v2
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar build
        run: npm run build

  publish:
    name: Publish on github
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: change directory
        run: ls
      - name: Deploy to foo-bar.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "testmaria101.surge.sh"
          project: "."
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}

      #- uses: actions/checkout@v2
      #- uses: actions/step-node@v1
      #  with:
      #    node-version: 10
      #    run: npm ci
      #    run: npm test
