name: Continues integration with nodejs

on:
  pull_request:
    branches: [main]

jobs:
  #build:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: CLonar y ubicarse en la rama main
        uses: actions/checkout@v2
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar test
        run: npm test

      #- uses: actions/checkout@v2
      #- uses: actions/step-node@v1
      #  with:
      #    node-version: 10
      #    run: npm ci
      #    run: npm test
